version: 2
jobs:
  deploy:
    docker:
      - image: circleci/node:8.10
    steps:
      - checkout
      - run:
          name: Install awscli, jq and npm
          command: |
            apt-get update
            apt-get install -y jq zip python3-pip
            pip3 install awscli --upgrade
            curl -sL https://deb.nodesource.com/setup_8.x | bash -
            apt-get install -y nodejs
            npm install -g npm@5
            aws configure set default.region $AWS_REGION
      - run:
          name: Install dependencies
          command: |
            cd functions
            cd compressImage
            npm install
      - run:
          name: Deploy functions
          command: |
            cd functions
            ../.circleci/deploy.sh echo
workflows:
  version: 2
  full:
    jobs:
      - deploy:
          filters:
            branches:
              only: master
              